openapi: 3.2.0
info:
  title: Ordoro API Documentation Tag API
  description: '# Introduction


    The Ordoro API can be used to access data or integrate to add functionality to Ordoro.'
  contact: {}
  version: '1.0'
servers:
- url: https://api.ordoro.com/
  variables: {}
tags:
- name: Tag
  description: ''
paths:
  /v3/order/{order_number}/tag/{tag_id}:
    post:
      summary: Add a tag to an order
      operationId: OrderbyOrderNumberAndTagByID_POST
      tags:
      - Tag
      parameters:
      - $ref: '#/components/parameters/orderNumberPath'
      - name: tag_id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              example:
              - link: /tag/2
                color: '#FF0'
                text: Alert
                id: 2
              - link: /tag/1
                color: '#C0C0C0'
                text: hold
                id: 1
              schema:
                $ref: '#/components/schemas/tags'
    delete:
      summary: Remove tag from order
      operationId: OrderbyOrderNumberAndTagByID_DELETE
      tags:
      - Tag
      parameters:
      - $ref: '#/components/parameters/orderNumberPath'
      - name: tag_id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: 200 response OK
          content:
            application/json:
              example:
              - link: /tag/2
                color: '#FF0'
                text: Alert
                id: 2
              schema:
                $ref: '#/components/schemas/tags'
  /v3/tag:
    get:
      summary: Get a list of Order tags
      operationId: V3Tag_GET
      tags:
      - Tag
      parameters:
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: response OK
          content:
            application/json:
              example:
                count: 2
                tag:
                - color: '#ff0'
                  text: Unpaid
                  link: /tag/1
                  id: 1
                - color: '#f7dbe7'
                  text: Tag
                  link: /tag/3
                  id: 3
                limit: 10
                offset: 0
              schema:
                $ref: '#/components/schemas/tag_list'
    post:
      summary: Create an Order Tag
      operationId: V3Tag_POST
      tags:
      - Tag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_tag'
      responses:
        '200':
          description: response OK
          content:
            application/json:
              example:
                color: purple
                text: mytag
                link: /tag/1
                id: 1
              schema:
                $ref: '#/components/schemas/tag'
  /v3/tag/{tag_id}:
    get:
      summary: Get an Order Tag by ID
      operationId: V3TagById_GET
      tags:
      - Tag
      parameters:
      - name: tag_id
        type: string
        in: path
        required: true
      responses:
        '200':
          description: response OK
          content:
            application/json:
              example:
                color: '#ff0'
                text: Unpaid
                link: /tag/3
                id: 3
              schema:
                $ref: '#/components/schemas/tag'
    put:
      summary: Update an Order Tag
      operationId: V3TagById_PUT
      tags:
      - Tag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/put_tag'
      parameters:
      - name: tag_id
        type: string
        in: path
        required: true
      responses:
        '200':
          description: response OK
          content:
            application/json:
              example:
                color: '#fff0'
                text: Unpaid
                link: /tag/3
                id: 3
              schema:
                $ref: '#/components/schemas/tag'
    delete:
      summary: Delete an Order Tag
      operationId: V3TagById_DELETE
      tags:
      - Tag
      parameters:
      - name: tag_id
        type: string
        in: path
        required: true
      responses:
        '200':
          description: response OK
components:
  parameters:
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    orderNumberPath:
      description: Unique identifier for an Order that includes a cart index prefix
      name: order_number
      schema:
        type: string
      in: path
      required: true
    offsetParam:
      in: query
      name: offset
      required: false
      description: ''
      schema:
        type: integer
        default: 0
        minimum: 0
  schemas:
    tags:
      title: Post Order Tag Response
      type: array
      items:
        $ref: '#/components/schemas/tag'
    put_tag:
      title: Update Tag Schema
      type: object
      properties:
        color:
          type: string
        text:
          type: string
      additionalProperties: false
    tag_list:
      title: Tag List Schema
      type: object
      properties:
        count:
          type: integer
        tag:
          type: array
          items:
            $ref: '#/components/schemas/tag'
        limit:
          type: integer
          default: 10
        offset:
          type: integer
          default: 0
      required:
      - count
      - tag
      - limit
      - offset
    tag:
      title: Tag Schema
      type: object
      properties:
        color:
          type: string
        text:
          type: string
        name:
          type: string
        link:
          type: string
        id:
          type: integer
      required:
      - color
      - text
      - link
      - id
    post_tag:
      title: Create Tag Schema
      type: object
      properties:
        color:
          type: string
        text:
          type: string
      additionalProperties: false
      required:
      - color
      - text
